### ISSUE TITLE
Instruction missing to install bunyan using npm

### ISSUE THREAD

**Issue by Shwetajain148** [MauriceButler/bunyan-loggly#25]
Hi,

As shown in your usage example in the readme file that we require both `bunyan` and `bunyan-loggly` to setup the logging you must also provide explicit instructions to run both the commands `npm install bunyan` and `npm install bunyan-loggly`. If we only run the command `npm install bunyan-loggly` then we get the below error-

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'bunyan'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dell/bunyan-loggly/testbun.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

After installing `bunyan`, logging works fine.

**Comment by MauriceButler** [comment]
Hi @Shwetajain148 

This module itself does not depend on the `bunyan` module, hence it is not included when `bunyan-loggly` is installed.

In the example in the readme it is shown using `bunyan` as it is assumed this will already be in place but any other logging module with a similar output could be use.
